name: "🐞 Bug Report"
description: "Report a software bug or unexpected behavior"
labels: ["type: bug", "priority: high"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for reporting a bug! 
        Please fill out this form as accurately as possible to help us fix the issue quickly.
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Initialize Matcher with...
        2. Call method X...
        3. Observe error Y...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      placeholder: "What did you expect to happen?"
    validations:
      required: true
  - type: input
    id: gambas_version
    attributes:
      label: "Gambas Version"
      placeholder: "e.g., 3.19.1"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "Operating System"
      placeholder: "e.g., Ubuntu 22.04, Debian 12, etc."
  - type: textarea
    id: logs
    attributes:
      label: "Logs or Error Output"
      description: "Copy-paste any terminal output or Gambas error messages here."
      render: shell
  - type: checkboxes
    id: confirmation
    attributes:
      label: "Verification"
      options:
        - label: "I have checked that this bug hasn't been reported already."
          required: true
        - label: "I am using the latest version of Gambas Matcher Mock."
          required: true