name: "🏗️ Epic / Major Feature"
description: "Plan a major feature or a significant refactoring"
labels: ["epic", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Epic Definition
        Use this template for large-scale work that requires multiple Pull Requests.
  - type: textarea
    id: overview
    attributes:
      label: "Vision & Objective"
      placeholder: "What major problem are we trying to solve?"
    validations:
      required: true
  - type: textarea
    id: user_stories
    attributes:
      label: "User Stories / Use Cases"
      placeholder: |
        - As a developer, I want to be able to...
        - As an end user, I want to...
  - type: textarea
    id: technical_design
    attributes:
      label: "Technical Design & Architecture"
      placeholder: "Describe the new classes, modules, or planned structural changes."
  - type: textarea
    id: tasks
    attributes:
      label: "📋 Task List (Roadmap)"
      placeholder: |
        - [ ] Create class X
        - [ ] Implement interface Y
        - [ ] Document new methods
        - [ ] Unit tests
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      placeholder: "Why did we choose this approach over another?"
  - type: checkboxes
    id: checks
    attributes:
      label: "Acceptance Criteria"
      options:
        - label: "Code is 100% tested"
          required: true
        - label: "Documentation is updated"
          required: true
        - label: "Examples in `examples/` are functional"
          required: true