name: "🏗️ Epic / Grosse Feature"
description: "Planifier une fonctionnalité majeure ou une refonte"
labels: ["epic", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Définition de l'Epic
        Utilisez ce template pour les travaux d'envergure qui nécessitent plusieurs Pull Requests.
  - type: textarea
    id: overview
    attributes:
      label: "Vision & Objectif"
      placeholder: "Quel problème majeur essayons-nous de résoudre ?"
    validations:
      required: true
  - type: textarea
    id: user_stories
    attributes:
      label: "User Stories / Cas d'usage"
      placeholder: |
        - En tant que développeur, je veux pouvoir...
        - En tant qu'utilisateur final, je souhaite...
  - type: textarea
    id: technical_design
    attributes:
      label: "Architecture & Design technique"
      placeholder: "Décrivez les nouvelles classes, modules ou changements de structure prévus."
  - type: textarea
    id: tasks
    attributes:
      label: "📋 Liste des tâches (Roadmap)"
      placeholder: |
        - [ ] Création de la classe X
        - [ ] Implémentation de l'interface Y
        - [ ] Documentation des nouvelles méthodes
        - [ ] Tests unitaires
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives envisagées"
      placeholder: "Pourquoi avons-nous choisi cette approche plutôt qu'une autre ?"
  - type: checkboxes
    id: checks
    attributes:
      label: "Critères d'acceptation"
      options:
        - label: "Le code est testé à 100%"
          required: true
        - label: "La documentation est mise à jour"
          required: true
        - label: "Les exemples dans `examples/` sont fonctionnels"
          required: true